### ISSUE TITLE
Listen tcp4 0.0.0.0:53: bind: address already in use

### ISSUE THREAD

**Issue by keobr** [MultiDirectoryLab/MultiDirectory#362]
After run docker-compose.yml I have an error:

Error response from daemon: driver failed programming external connectivity on endpoint traefik (44f4c1dac2d48252658c65fda096d833da1f7eda07533bd2549a506967579882): failed to bind port 0.0.0.0:53/tcp: Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use

since the port is in use, containers do not start

NAME="Fedora Linux"
VERSION="40 (Workstation Edition)"
ID=fedora
VERSION_ID=40
 
Docker version 27.3.1, build ce12230
docker-compose version 1.29.2
![Screenshot from 2024-10-16 09-12-17](https://github.com/user-attachments/assets/0107cbda-e2c4-471d-8c95-02b22958f489)

**Comment by main1byte** [comment]
> После запуска docker-compose.yml у меня возникает ошибка:
> 
> Ошибка ответа от демона: драйверу не удалось запрограммировать внешнее подключение на конечной точке traefik (44f4c1dac2d48252658c65fda096d833da1f7eda07533bd2549a506967579882): не удалось привязать порт 0.0.0.0:53/tcp: Ошибка запуска прокси-сервера пользовательского пространства: прослушивание tcp4 0.0.0.0:53: привязка: адрес уже используется
> 
> так как порт используется, контейнеры не запускаются
> 
> NAME="Fedora Linux" VERSION="40 (редакция для рабочей станции)" ID=fedora VERSION_ID=40
> 
> Docker версии 27.3.1, сборка ce12230 docker-compose версии 1.29.2 ![Скриншот от 2024-10-16 09-12-17](https://private-user-images.githubusercontent.com/47155091/376913007-0107cbda-e2c4-471d-8c95-02b22958f489.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDk2MjQsIm5iZiI6MTcyOTE0OTMyNCwicGF0aCI6Ii80NzE1NTA5MS8zNzY5MTMwMDctMDEwN2NiZGEtZTJjNC00NzFkLThjOTUtMDJiMjI5NThmNDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA3MTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwNTVlYmZhNzdiM2EzMWIzYmQ4MWI1OTBhYzAyNGNlMjhmZWM2M2UwZDBmZjlkZGY2MGIyMTY1OTRmMDFjODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q-Wus--P_GtGNh5GvsUAupc1HmHUA3BX3CB2ZGUC9uo)

У федоры нужно отключить dns resolver
Так-же указать 
etc/systemd/resolved.conf
DNSStubListener=no

Собственно с такой проблемой можно столкнуться и на убунте.
Дебиан 12  не стартует эту службу, поэтому 53 порт свободен.
